### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by juliocbcotta** [caoyunxiao/photo_album_manager#1]
Hey, how about to migrate to AndroidX?

**Comment by charlesYun** [comment]
This issue has been resolved in tonight's edition

**Comment by juliocbcotta** [comment]
this dependency is not in AndroidX https://github.com/caoyunxiao/photo_album_manager/blob/master/android/build.gradle#L37

How about to update it?

**Comment by charlesYun** [comment]
You can get the latest version, the problem has been solved

**Comment by juliocbcotta** [comment]
Thank you!
