### ISSUE TITLE
安卓视频被重命名以后，还是会读到之前的路径，然后拿着这个路径播放的话就会报错

### ISSUE THREAD

**Issue by Zuozihao** [caoyunxiao/photo_album_manager#13]
缓存很严重，在相册里将视频删除后 还是会读到路径和缩略图。

**Comment by Zuozihao** [comment]
缓存很严重，在相册里将视频删除后 还是会读到路径和缩略图。

**Comment by charlesYun** [comment]
安卓还是iOS


Caoyunxiao


在2020年10月12日 14:58，Zuozihao<notifications@github.com> 写道：

缓存很严重，在相册里将视频删除后 还是会读到路径和缩略图。

**Comment by Zuozihao** [comment]
> 安卓还是iOS Caoyunxiao 在2020年10月12日 14:58，Zuozihao<notifications@github.com> 写道： 缓存很严重，在相册里将视频删除后 还是会读到路径和缩略图。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

安卓
