### ISSUE TITLE
release打包安装后app闪退

### ISSUE THREAD

**Issue by ASentimentalMan** [caoyunxiao/photo_album_manager#6]
BUG情况：debug时没有问题，打包release时报错：
```
warning: unknown enum constant ThreadMode.POSTING                       
  reason: class file for org.greenrobot.eventbus.ThreadMode not found   
1 warning   
```
继续安装apk后打开时闪退
从pubspec.yaml中删除photo_album_manager: ^1.1.2重新打包就不闪退了
确定是photo_album_manager的问题

flutter版本：1.17.2

**Comment by charlesYun** [comment]
photo_album_manager: [^1.1.3](https://pub.dev/packages/photo_album_manager#-readme-tab-)
