### ISSUE TITLE
在夜神模拟器会自动copy图片。并将图片放在pic文件夹里面

### ISSUE THREAD

**Issue by dazed-daydreamer** [caoyunxiao/photo_album_manager#8]
![微信图片_20200619112135](https://user-images.githubusercontent.com/48002442/85093502-15576200-b21f-11ea-8a45-fb67fa13f57a.png)

请问如何阻止阻止这个情况发生？每次调用 PhotoAlbumManager.getDescAlbumImg 后再打开相册就会copy一份原图。

**Comment by charlesYun** [comment]
Pic 目录是缓存目录，主要是为了提供文件路径。你的意思是图片会重复吗？已经缓存的再次调用PhotoAlbumManager.getDescAlbumImg还会再缓存一张




在2020年06月19日 11:23，343629302<notifications@github.com> 写道：

请问如何阻止阻止这个情况发生？每次调用 PhotoAlbumManager.getDescAlbumImg 后再打开相册就会copy一份原图。

**Comment by dazed-daydreamer** [comment]
就是我本来只有10张图片的。每次调用PhotoAlbumManager.getDescAlbumImg 就会增加10张图片。调用2次就如上图一样变成20张图片。并且PhotoAlbumManager.getDescAlbumImg 会返回全部图片30张。那不是出大问题了···。

**Comment by dazed-daydreamer** [comment]
我只想获取本地图片,但是你就帮我复制了一堆图片。

**Comment by dazed-daydreamer** [comment]
> Pic 目录是缓存目录，主要是为了提供文件路径。你的意思是图片会重复吗？已经缓存的再次调用PhotoAlbumManager.getDescAlbumImg还会再缓存一张 在2020年06月19日 11:23，343629302<notifications@github.com> 写道： 请问如何阻止阻止这个情况发生？每次调用 PhotoAlbumManager.getDescAlbumImg 后再打开相册就会copy一份原图。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

每次调用都缓存。但是不删除缓存。那么第二次再调用就是获取到20张图片了。10张原图。10张copy的图。

**Comment by charlesYun** [comment]
如果缓存重复了肯定是不对的， 我检查一下，周末更新一个版本


在2020年06月19日 11:44，343629302<notifications@github.com> 写道：

我只想获取本地图片,但是你就帮我复制了一堆图片。

**Comment by charlesYun** [comment]
https://pub.dev/packages/photo_album_manager

试试photo_album_manager: ^1.1.6


在2020年06月19日 12:12，chinacgcgcg<chinacgcgcg@163.com> 写道：
如果缓存重复了肯定是不对的， 我检查一下，周末更新一个版本


在2020年06月19日 11:44，343629302<notifications@github.com> 写道：

我只想获取本地图片,但是你就帮我复制了一堆图片。
