### ISSUE TITLE
版本photo_album_manager1.1.6 无法获取到其他文件的缩略图

### ISSUE THREAD

**Issue by zglnfsdyy** [caoyunxiao/photo_album_manager#9]
视频或者图片。无法获取到在qq文件里的视频或者图片的缩略图。我同样获取本地相机的拍照的图片的缩略图。也是无法获取到的。thumbPath显示是null。originalPath和ilocalIdentifier则是存在的

**Comment by charlesYun** [comment]
你试着安装一下 demo 贴出的二维码看看是否正常

**Comment by zglnfsdyy** [comment]
> 你试着安装一下 demo 贴出的二维码看看是否正常

我安卓了。也是部分图片或者视频的缩略图未显示。在flutter这边获取thumbPath则显示为null

**Comment by zglnfsdyy** [comment]
1.我是用qq截取的图片。通过qq传输到手机。保存到手机上的。

**Comment by charlesYun** [comment]
是在文件夹还是在相册呢？如果thumbPath为null， 你可以看看originalPath 是否正常，不排除个别资源无法获取缩略图的情况

**Comment by zglnfsdyy** [comment]
> 是在文件夹还是在相册呢？如果thumbPath为null， 你可以看看originalPath 是否正常，不排除个别资源无法获取缩略图的情况

图片是在文件夹里。originalPath能获取到。但是若是类型是video的情况。缩略图是无法获取到。但是恢复以前的版本就可以。最新的就不行了。但是以前的版本会存在图片在相册里不断增长。我现在不知道该怎么处理这个问题了。我需要显示视频的缩略图

**Comment by charlesYun** [comment]
是个别资源吗？我查一查

**Comment by zglnfsdyy** [comment]
我使用了小红书的视频资源：http://v.xiaohongshu.com/c65b1436bd986b3939e094085c6229a5e5ee6a54_v1?sign=c0ad19ed4437baf0adc6a961526cec3a&t=5ef76d00        另存为11.mp4之后，通过qq传输。存到手机里。获取的时候无法获取到缩略图

**Comment by charlesYun** [comment]
试试 photo_album_manager: ^1.1.7

**Comment by zglnfsdyy** [comment]
> 试试 photo_album_manager: ^1.1.7

好的。非常感谢。这个问题已经解决了。
